name: Build
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/RESTSchemaRetry/RESTSchemaRetry.csproj
      
    - name: Restore dependencies for Test Project
      run: dotnet restore src/RESTSchemaRetry.Test/RESTSchemaRetry.Test.csproj
      
    - name: Build
      run: dotnet build src/RESTSchemaRetry/RESTSchemaRetry.csproj --no-restore
      
    - name: Build Test Project
      run: dotnet build src/RESTSchemaRetry.Test/RESTSchemaRetry.Test.csproj --no-restore
      
    - name: Test
      run: dotnet test src/RESTSchemaRetry.Test/RESTSchemaRetry.Test.csproj --no-build --verbosity normal
